#!/bin/bash
#
. "$(dirname "$(readlink -f "$0")")/utils/init.sh"
. $utlib/pm.sh
. $utlib/unitest.sh

trap 'exit $retcode' EXIT

[ ! -f plugin.yml ] && fatal "No plugin.yml"
[ -f README.md ] && $gd3tool gen -w src utils *.php

if [ -d resources/messages ] ; then
  $mcgen gen resources/messages src
  $mcgen enc resources/messages
fi
$mkver src
ymlver=$($mkver)
if [ -n "$ymlver" ] ; then
  if [ -n "$TRAVIS_TAG" ] ; then
    if [ "$ymlver" != "$TRAVIS_TAG" ] ; then
      fail "Plugin.yml version and git tag mismatch"
    fi
  fi
else
  fail "Unknown plugin.yml version"
fi

phplint src utils *.php || fatal "Failed lint"

#LINUX_BUILD="PHP_7.0.3_x86-64_Linux"
#wget -nv -O- "https://dl.bintray.com/pocketmine/PocketMine/$LINUX_BUILD.tar.gz" | tar -zx > /dev/null 2>&1
#chmod +x ./bin/php7/bin/*
#./bin/php7/bin/php -r 'echo 1;'

install_pocketmine

$phpcmd $scriptdir/mkplugin.php -o $MPDIR/plugins .

testgroup="$(default_tests t "$@")"
[ -z "$testgroup" ] && exit

runtests $testgroup

show_results
